# Generated by Django 4.1 on 2022-09-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('value', models.IntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('surname', models.CharField(max_length=150, verbose_name='Apellido')),
                ('motivo_social', models.CharField(max_length=20, verbose_name='Razon social')),
                ('document', models.BigIntegerField(verbose_name='Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('addres', models.CharField(max_length=150, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipopqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'tipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=150, verbose_name='Apellido')),
                ('document', models.BigIntegerField(verbose_name='Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('addres', models.CharField(max_length=150, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=150, verbose_name='Apellido')),
                ('tel', models.IntegerField(verbose_name='telefono')),
                ('description', models.TextField(verbose_name='Comentario')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('Tipopqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.tipopqrs')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
                'db_table': 'pqrs',
                'ordering': ['id'],
            },
        ),
    ]
