# Generated by Django 4.1 on 2022-10-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_registrarpedidos_delete_pedidoproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrarpedidos',
            name='soporte_factura',
            field=models.FileField(default='', upload_to='', verbose_name='Soporte Factura'),
            preserve_default=False,
        ),
    ]
