# Generated by Django 4.1 on 2022-10-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_registrarpedidos_soporte_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='surname',
        ),
    ]
