# Generated by Django 4.1 on 2022-10-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddres',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='linea1',
            field=models.CharField(max_length=200, verbose_name='Direccion 1'),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='linea2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Direccion 2'),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='reference',
            field=models.CharField(max_length=300, verbose_name='Anotacion'),
        ),
        migrations.AlterField(
            model_name='shippingaddres',
            name='state',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
    ]
